[2024-09-14T14:23:24.942+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Dag_S3.extract_hr scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-14T14:23:24.967+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Dag_S3.extract_hr scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-14T14:23:24.968+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-09-14T14:23:25.014+0000] {taskinstance.py:2191} INFO - Executing <Task(SqlToS3Operator): extract_hr> on 2024-09-13 00:00:00+00:00
[2024-09-14T14:23:25.025+0000] {standard_task_runner.py:60} INFO - Started process 215 to run task
[2024-09-14T14:23:25.047+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Dag_S3', 'extract_hr', 'scheduled__2024-09-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag_s3.py', '--cfg-path', '/tmp/tmprw1srzal']
[2024-09-14T14:23:25.052+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask extract_hr
[2024-09-14T14:23:25.154+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_Dag_S3.extract_hr scheduled__2024-09-13T00:00:00+00:00 [running]> on host 12663b3bf2f5
[2024-09-14T14:23:25.329+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jasontran' AIRFLOW_CTX_DAG_ID='ETL_Dag_S3' AIRFLOW_CTX_TASK_ID='extract_hr' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T00:00:00+00:00'
[2024-09-14T14:23:25.375+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 176, in execute
    sql_hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 208, in _get_hook
    conn = BaseHook.get_connection(self.sql_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `PostgreSQL_conn` isn't defined
[2024-09-14T14:23:25.385+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Dag_S3, task_id=extract_hr, execution_date=20240913T000000, start_date=20240914T142324, end_date=20240914T142325
[2024-09-14T14:23:25.422+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task extract_hr (The conn_id `PostgreSQL_conn` isn't defined; 215)
[2024-09-14T14:23:25.454+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-14T14:23:25.497+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
