[2024-08-31T17:28:00.130+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Dag_S3.snowflake_insert_task scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T17:28:00.151+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Dag_S3.snowflake_insert_task scheduled__2024-08-30T00:00:00+00:00 [queued]>
[2024-08-31T17:28:00.152+0000] {taskinstance.py:2170} INFO - Starting attempt 36 of 40
[2024-08-31T17:28:00.179+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): snowflake_insert_task> on 2024-08-30 00:00:00+00:00
[2024-08-31T17:28:00.188+0000] {standard_task_runner.py:60} INFO - Started process 252 to run task
[2024-08-31T17:28:00.193+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ETL_Dag_S3', 'snowflake_insert_task', 'scheduled__2024-08-30T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag_s3.py', '--cfg-path', '/tmp/tmptkzbl2um']
[2024-08-31T17:28:00.200+0000] {standard_task_runner.py:88} INFO - Job 259: Subtask snowflake_insert_task
[2024-08-31T17:28:00.292+0000] {task_command.py:423} INFO - Running <TaskInstance: ETL_Dag_S3.snowflake_insert_task scheduled__2024-08-30T00:00:00+00:00 [running]> on host f6a0ecf2184f
[2024-08-31T17:28:00.501+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jasontran' AIRFLOW_CTX_DAG_ID='ETL_Dag_S3' AIRFLOW_CTX_TASK_ID='snowflake_insert_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='36' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-30T00:00:00+00:00'
[2024-08-31T17:28:00.504+0000] {sql.py:276} INFO - Executing: 
    insert into ***_db.tcops_dimensions.employee_dim (employee_surrogate_key, employee_id, employee_name, employee_email, job, supervisor_name, company, org_level_3, org_level_2, org_level_1, org_level_4, last_hire_date, termination_date, effective_start_date, effective_end_date, is_active)
    values None
    
[2024-08-31T17:28:00.522+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-08-31T17:28:00.540+0000] {base.py:83} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-08-31T17:28:00.541+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-08-31T17:28:00.542+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-31T17:28:02.459+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-08-31T17:28:02.604+0000] {cursor.py:1041} INFO - query execution done
[2024-08-31T17:28:02.606+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-08-31T17:28:02.608+0000] {sql.py:450} INFO - Running statement: insert into ***_db.tcops_dimensions.employee_dim (employee_surrogate_key, employee_id, employee_name, employee_email, job, supervisor_name, company, org_level_3, org_level_2, org_level_1, org_level_4, last_hire_date, termination_date, effective_start_date, effective_end_date, is_active)
    values None, parameters: None
[2024-08-31T17:28:02.615+0000] {cursor.py:1028} INFO - query: [insert into ***_db.tcops_dimensions.employee_dim (employee_surrogate_key, em...]
[2024-08-31T17:28:02.728+0000] {cursor.py:1041} INFO - query execution done
[2024-08-31T17:28:02.736+0000] {connection.py:718} INFO - closed
[2024-08-31T17:28:02.964+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-08-31T17:28:03.041+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01b6b8d8-3201-332a-0009-fca600021e9a: SQL compilation error:
syntax error line 2 at position 11 unexpected 'None'.
syntax error line 2 at position 15 unexpected '<EOF>'.
[2024-08-31T17:28:03.058+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_Dag_S3, task_id=snowflake_insert_task, execution_date=20240830T000000, start_date=20240831T172800, end_date=20240831T172803
[2024-08-31T17:28:03.094+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 259 for task snowflake_insert_task (001003 (42000): 01b6b8d8-3201-332a-0009-fca600021e9a: SQL compilation error:
syntax error line 2 at position 11 unexpected 'None'.
syntax error line 2 at position 15 unexpected '<EOF>'.; 252)
[2024-08-31T17:28:03.146+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T17:28:03.173+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
